DROP SCHEMA IF EXISTS `crm_project`;

CREATE SCHEMA `crm_project`;

USE `crm_project`;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `customers`;
CREATE TABLE `customers` (
	`id` INT(11) PRIMARY KEY AUTO_INCREMENT,
	`first_name` VARCHAR(50) DEFAULT NULL,
	`last_name` VARCHAR(50) DEFAULT NULL,
	`email` VARCHAR(200) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1001 DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;
